
#Install packages if first time
install.packages('dplyr')
install.packages('readr')
install.packages('tidyr')
install.packages('stringr')
install.packages('forcats')
install.packages('purr')
install.packages("ggpubr")


#Read in Packages needed
library(dplyr) # manipulate dataframes
library(readr) # read/write dataframes
library(tidyr) # reshaping dataframes
library(stringr) # string manipulation
library(forcats) # factor manipulation
library(purrr) # iteration (instead of loops)
library(ggpubr) # for Correlation
library(ggplot2) # for Plots

#Import the data- ANES Survey Timeseries
library(haven)
> anes_timeseries_cdf_stata13 <- read_dta("~/Documents/School/Syllabus/MZ FINAL PRO/anes_timeseries_cdf_stata13.dta")

#Filter to 2004

Updated1 <-anes_timeseries_cdf_stata13[!(anes_timeseries_cdf_stata13$VCF0004<"2004"),]

# select variables 

Filtered = subset(Updated1, select = c(
  VCF0004, VCF0102, VCF0103, VCF0104,VCF0105a, VCF0105b,VCF0106,VCF0107, VCF0700,
  VCF0201,VCF0202, VCF0301 ,VCF0303, VCF0314 ,VCF0315 ,VCF0323 ,VCF0501,VCF9008,VCF9010 ,VCF9011,VCF9012,
  VCF9201,VCF9202 ,VCF9203,VCF9204,VCF9206,VCF0350 ,VCF0351 ,VCF0352,VCF0353 , VCF0354 ,VCF0355 ,
  VCF0356 ,VCF0357 ,VCF0358 ,VCF0363 ,VCF0364,VCF0365 ,VCF0366 ,VCF0367, VCF0368 ,VCF0369 ,VCF0370 ,
  VCF0371 ,VCF0372,VCF0373 ,VCF0412 ,VCF0414 ,VCF0906 ,VCF0907,VCF0908 ,VCF0909 ,VCF0450,VCF0451,VCF9217,
  VCF9218,  VCF9220,VCF9221,VCF0875 ,VCF0875a ,VCF0875b ,VCF9019,VCF9020 ,VCF9052,VCF9222,VCF0803,VCF9240, VCF0228 ,VCF0231 ,VCF0601,VCF0602 , VCF0603 ,
  VCF0604 ,VCF0608 ,VCF0656,VCF9250,VCF9251,VCF9252,VCF9253,VCF9254,VCF9256,VCF9257,VCF0308,VCF0309,
  VCF0310,VCF0311,VCF0312,VCF0313,VCF0700,VCF0714,VCF0729 ,VCF0730,VCF0731,VCF0732,VCF0733,VCF0743,
  VCF0932,VCF0933,VCF0934,VCF0935,VCF0936,VCF0941, VCF0942, VCF0943, VCF0944, VCF0945 , VCF0946 ,VCF0947,
  VCF0948, VCF0949,VCF9064,VCF0717,VCF0723,VCF0723a,VCF0746,VCF0747 ,VCF9021 ,VCF9030,VCF9030a,
  VCF0701 ,VCF0702 , VCF0703 , VCF0704 , VCF0704a , VCF0705, VCF0706, VCF0707 , VCF0711, VCF0708,
  VCF0713 , VCF0712, VCF0748, VCF0749,VCF0750,VCF9022,VCF9023,VCF0675,VCF0724,VCF0725,VCF0726,VCF0727,
  VCF0728,VCF0744,VCF0745,VCF9032,VCF9033,VCF9034,VCF9035, VCF9266))



#Filter out the columns that are not relevant- have all missings (questions from older surveys (two ways)

Updated_data <- Filtered [ , colSums(is.na(Filtered)) <nrow(Filtered)]

data_new3 <- Filtered [ , colSums(is.na(Filtered)) <nrow(Filtered)]

#Descriptive Statistics 

#Connect to the correct frame 
attach(Updated_data)

summary(Updated_data)
summary(VCF0301)
summary(VCF0303)
summary(VCF0314)
summary(VCF0315)
summary(VCF0501)
summary(VCF9250)
summary(VCF0702)

#Add Labels
names(Updated_data)[names(Updated_data) == "VCF0301"] <- "Party Identification of Respondent-7-point Scale"
Updated_data

#Tables/Cross Tabs

#Voted-Contacted by a Major Party?
Table1 <- table(VCF0702, VCF9030a) 

#Voted
table(VCF0702)

#Diff b/w parties?
table(VCF0501)

table(VCF0702, VCF0501)

Dem_Voters <- table(VCF0702, VCF0314)
round(prop.table(Dem_Voters,1),2)

Diff_parties <- table(VCF0702, VCF0501)
Diff_parties
round(prop.table(Diff_parties,1),2)

(#Less incentivized to vote if think there the same)

Dislike_DEM <- table(VCF0702, VCF9201)
Dislike_DEM

Dislike_REP <- table(VCF0702, VCF9202)

Rep_views <- table(VCF0702, VCF9203)
round(prop.table(Rep_views,1),2)

which_party <- table(VCF0702, VCF9204)
round(prop.table(which_party,1),2)

Party_pref <- table(VCF0702, VCF9206)
round(prop.table(Party_pref,1),2)

Dem_Smart <- table(VCF0702, VCF0350)
round(prop.table(Dem_Smart,1),2)

Dem_Angry <- table(VCF0702, VCF0358)
round(prop.table(Dem_Angry,1),2)

REP_Angry <- table(VCF0702, VCF0370)
round(prop.table(REP_Angry,1),2)

Approve_Pres <- table(VCF0702, VCF0450)
round(prop.table(Approve_Pres,1),2)

Approve_Pres_rating <- table(VCF0702, VCF0451)
round(prop.table(Approve_Pres_rating,1),2)

Pres_Econ <- table(VCF0702, VCF9220)
round(prop.table(Pres_Econ,1),2)

Right_Track <- table(VCF0702, VCF9222)
round(prop.table(Right_Track,1),2)

LIB_CON <- table(VCF0702, VCF0803)
round(prop.table(LIB_CON,1),2)

Trust_Fed_Gov <- table(VCF0702, VCF0604)
round(prop.table(Trust_Fed_Gov,1),2)

Crooked_FED <- table(VCF0702, VCF0608)
round(prop.table(Crooked_FED,1),2)

TRUST_GOV_GEN <- table(VCF0702, VCF0656)
round(prop.table(TRUST_GOV_GEN,1),2)

Volunteer <- table(VCF0702, VCF9256)
round(prop.table(Volunteer,1),2)

Interst_Elec <- table(VCF0702, VCF0310)
round(prop.table(Interst_Elec,1),2)

Care_win <- table(VCF0702, VCF0311)
round(prop.table(Care_win,1),2)

Care_win_CONG <- table(VCF0702, VCF0312)
round(prop.table(Care_win_CONG,1),2)

Pred_Close <- table(VCF0702, VCF0714)
round(prop.table(Pred_Close,1),2)

Pred_Close

#Correlation

res <- cor.test(VCF0702, VCF0102, 
                method = "pearson")
res

#Regressions

Reg1 <- lm(VCF0702 ~ VCF0104 + VCF0303 + VCF0314 + VCF0501 + VCF0412, data=Updated_data)
summary(Reg1)



